version: '3.1'

services:
    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8080:80'

    php:
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        build: docker/php
        restart: always
        depends_on:
            - mysql
        volumes:
            - "./:/symfony"
        links:
            - mysql

    mysql:
        build: docker/mysql
        volumes:
            - "./:/symfony"
            - "mysql/:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: marnould
            MYSQL_PASSWORD: playmepass
            MYSQL_DATABASE: playme
        ports:
            - "3308:3306"

volumes:
  mysql:

