version: '3.1'

services:

    nginx:
        build: docker/nginx
        volumes:
            - "../src:/var/www"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx/sites/:/etc/nginx/sites-available"
            - "./nginx/conf.d/:/etc/nginx/conf.d"
            - "./logs:/var/log"
        restart: always
        depends_on:
            - php
        ports:
            - "86:80"

    php:
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        build: docker/php
        restart: always
        depends_on:
            - mysql
        volumes:
            - "./:/symfony"
        links:
            - mysql

    mysql:
        build: docker/mysql
        volumes:
            - "./:/symfony"
            - "mysql/:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: marnould
            MYSQL_PASSWORD: playmepass
            MYSQL_DATABASE: playme
        ports:
            - "3308:3306"

volumes:
  mysql:

