version: '3.1'

services:

    nginx:
        build:
            context: ./nginx
        volumes:
            - "../src:/var/www"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx/sites/:/etc/nginx/sites-available"
            - "./nginx/conf.d/:/etc/nginx/conf.d"
            - "./logs:/var/log"
        restart: always
        depends_on:
            - php-fpm
        links:
            - php
        ports:
            - "80:80"

    php-fpm:
        build:
            context: ./php-fpm
        depends_on:
            - mysql
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
            volumes:
                - ../src:/var/www
        restart: always

    mysql:
        build: docker/mysql
        volumes:
            - "./:/symfony"
            - "mysql/:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: marnould
            MYSQL_PASSWORD: playmepass
            MYSQL_DATABASE: playme
        ports:
            - "3308:3306"

volumes:
  mysql:

