version: '3.8'

services:
    postgres:
        image: postgres:12.4-alpine
        restart: on-failure
        environment:
            POSTGRES_DB: playme
            POSTGRES_USER: playme_usr
            POSTGRES_PASSWORD: 2345playMePasS35
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"

    php:
        build:
            context: .
            target: app_php
            dockerfile: Dockerfile_prod
        image: sf-docker/php:latest
        restart: on-failure
        depends_on:
            - postgres
        environment:
            APP_ENV: PROD
            PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}

    nginx:
        build:
            context: .
            target: app_nginx
        image: sf-docker/nginx:latest
        restart: on-failure
        depends_on:
            - php
        ports:
            - "8080:80"